const collectionNamesActionTypes = {
  FETCH_COLLECTION_NAMES_START: "FETCH_COLLECTION_NAMES_START",
  FETCH_COLLECTION_NAMES_SUCCESS: "FETCH_COLLCETION_NAMES_SUCCESS",
  FETCH_COLLECTION_NAMES_FAILURE: "FETCH_COLLCETION_NAMES_FAILURE",
};
export default collectionNamesActionTypes;