const myOrdersTypeActions = {
  FETCH_MY_ORDERS_START: "FETCH_MY_ORDERS_START",
  FETCH_MY_ORDERS_SUCCESS: "FETCH_MY_ORDERS_SUCCESS",
  FETCH_MY_ORDERS_FAILURE: "FETCH_MY_ORDERS_FAILURE",
};
export default myOrdersTypeActions;
