const authenticationActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  GOOGLE_AUTHENTICATION_START:
    "GOOGLE_AUTHENTICATION_START",
  GOOGLE_AUTHENTICATION_SUCCESS:
    "GOOGLE_AUTHENTICATION_SUCCESS",
  GOOGLE_AUTHENTICATION_FAILURE:
    "GOOGLE_AUTHENTICATION_FAILURE",
};
export default authenticationActionTypes;
