const authenticationActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  GOOGLE_AUTHENTICATION_INITIALIZE_START:
    "GOOGLE_AUTHENTICATION_INITIALIZE_START",
  GOOGLE_AUTHENTICATION_INITIALIZE_SUCCESS:
    "GOOGLE_AUTHENTICATION_INITIALIZE_SUCCESS",
  GOOGLE_AUTHENTICATION_INITIALIZE_FAILURE:
    "GOOGLE_AUTHENTICATION_INITIALIZE_FAILURE",
};
export default authenticationActionTypes;
