const checkoutActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREMENT_ITEM: "INCREMENT_ITEM",
  DECREMENT_ITEM: "DECREMENT_ITEM",
  PURGE_CHECKOUT_COLLECTION: "PURGE_CHECKOUT_COLLECTION",
};
export default checkoutActionTypes;
