const homePageCollectionsActionTypes = {
  FETCH_HOME_PAGE_COLLECTIONS_START: "FETCH_HOME_PAGE_COLLECTIONS_START",
  FETCH_HOME_PAGE_COLLECTIONS_SUCCESS: "FETCH_HOME_PAGE_COLLECTIONS_SUCCESS",
  FETCH_HOME_PAGE_COLLECTIONS_FAILURE: "FETCH_HOME_PAGE_COLLECTIONS_FAILURE",
};

export default homePageCollectionsActionTypes;
