const actualDeviceActionTypes = {
  FETCH_ACTUAL_DEVICE_START: "FETCH_ACTUAL_DEVICE_START",
  FETCH_ACTUAL_DEVICE_SUCCESS: "FETCH_ACTUAL_DEVICE_SUCCESS",
  FETCH_ACTUAL_DEVICE_FAILURE: "FETCH_ACTUAL_DEVICE_FAILURE",
  REMOVE_ACTUAL_DEVICE: "REMOVE_ACTUAL_DEVICE",
};

export default actualDeviceActionTypes;
