export const userActionTypes = {
  FETCH_USER_LOGIN_ASYN: "FETCH_USER_LOGIN_ASYN",
  FETCH_USER_LOGIN_START: "FETCH_USER_LOGIN_START",
  FETCH_USER_LOGIN_SUCCESS: "FETCH_USER_LOGIN_SUCCESS",
  FETCH_USER_LOGIN_FAILURE: "FETCH_USER_LOGIN_FAILURE",
  FETCH_USER_REGISTER_ASYNC: "FETCH_USER_REGISTER_ASYNC",
  FETCH_USER_REGISTER_START: "FETCH_USER_REGISTER_START",
  FETCH_USER_REGISTER_SUCCESS: "FETCH_USER_REGISTER_SUCCESS",
  FETCH_USER_REGISTER_FAILURE: "FETCH_USER_REGISTER_FAILURE",
};
